### ISSUE TITLE
Can't use 'Diagnosticable' as a mixin because it has constructors.

### ISSUE THREAD

**Issue by amit0510** [syncfusion/flutter-examples#172]
![image](https://user-images.githubusercontent.com/38829682/88367112-8fdc4a00-cda8-11ea-8843-f29c4d2cadfc.png)

Getting this error when try to use `syncfusion_flutter_gauges: ^18.2.44`. I already used `syncfusion_flutter_charts: ^1.0.0-beta.3` and its working fine. When import `import 'package:syncfusion_flutter_gauges/gauges.dart';`, it give an error on that screen.

Help me to sort out this issue.

Following is my pubspec.yaml

```
name: flexi_profiler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3
  carousel_slider: ^1.3.0
  autocomplete_textfield: ^1.7.3
  flutter_tagging: ^1.0.1
  expressions: ^0.1.3
  intl: ^0.16.0
  json_table: ^1.3.2
  flutter_spinkit: ^4.1.1
  http: ^0.12.0+4
  xml: any
  xml2json: any
  syncfusion_flutter_charts: ^18.2.44
  sqflite: any
  path_provider: any
  url_launcher: ^5.0.3
  get_it: ^1.0.3+2
  month_picker_dialog: any
  image_picker: ^0.6.4
  table_calendar: ^2.2.3
  uuid: 2.0.4
  expandable: ^4.1.3
  shared_preferences: ^0.5.1+2
  connectivity: ^0.4.8+6
  firebase_messaging: ^6.0.16
  table_sticky_headers: ^1.1.2
  horizontal_data_table: any
  spear_menu: ^0.0.2
  flutter_widget_from_html: ^0.3.3+4
  pdf_viewer_plugin: ^1.0.0+2
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_slidable: "^0.5.4"
  tree_view: ^0.0.5

  firebase_core: "0.4.4"
  firebase_analytics: "5.0.11"
  firebase_auth: "0.15.4"
  firebase_storage: "3.1.1"
  cloud_firestore: "0.13.2+1"
  provider: "4.0.4"
  timeago: "2.0.26"
  photo_view: ^0.5.0
  google_sign_in: ^4.0.7
  flutter_local_notifications: 1.4.0
  validators: ^1.0.0+1
  jaguar_serializer: "^2.2.6"
  syncfusion_flutter_gauges: ^18.2.44



#  pdftron_flutter:
#    git:
#      url: git://github.com/PDFTron/pdftron-flutter.git
#  google_maps_flutter: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/AddList.png
    - assets/images/AIR.png
    - assets/images/Calendar.png
    - assets/images/Customer.png
    - assets/images/DCREntry.png
    - assets/images/DCRSummary.png
    - assets/images/Drug.png
    - assets/images/Expense.png
    - assets/images/KPI.png
    - assets/images/Map.png
    - assets/images/Professional.png
    - assets/images/Territory.png
    - assets/images/profiler_logo_new.png
    - assets/images/dashbord_background.png
    - assets/images/default_user.png
    - assets/images/Inbox.png
    - assets/images/attachment_inbox.png
    - assets/images/bottom_menu/settings.png
    - assets/images/bottom_menu/list.png
    - assets/images/bottom_menu/calendar.png
    - assets/images/bottom_menu/survey.png

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/TimesNewRoman.ttf
        - asset: assets/fonts/TimesNewRomanGras.ttf
        - asset: assets/fonts/TimesNewRomanGrasItalique.ttf
        - asset: assets/fonts/TimesNewRomanItalique.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 500

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Light.ttf
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Thin.ttf
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf

  uses-material-design: true
```
