### ISSUE TITLE
flutter calendar type error while using drag and drop.

### ISSUE THREAD

**Issue by rawquesh** [syncfusion/flutter-examples#486]
first of all its a great package, well there is an issue if we use a custom class in DataSource as an appointment class if you test this one of your examples with enabling drag and drop [link](https://github.com/SyncfusionExamples/custom-appointment-with-additional-attribute-flutter-event-calendar), after dropping the drag it will give Type error something like this one 

![Screenshot 2021-11-24 174311](https://user-images.githubusercontent.com/27288409/143237012-e200458d-ffe5-491d-b490-f70d8f0638d9.png)

please test the same example and you will see this error, [link](https://github.com/SyncfusionExamples/custom-appointment-with-additional-attribute-flutter-event-calendar)

```
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^19.3.55
```
